name: Mohican Arms
favicon: null
layout_spectrum: 0.9284438884351403
typography_spectrum: 0.4861523450817913
title: Mohican Arms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5868168328888714
  lightness: 0.8644459783099592
  saturation: 0.09250718471594155
  rhythmicContrast: 0.47123473533429205
purpose: []
