name: Mohican Arms
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70209
title: Mohican Arms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000075'
    - '#6a0000'
    - '#c9c9e2'
    - '#945555'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
